name: Mirror GitHub to NCP SourceCommit

on:
  push:
    branches:
      - "**"

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git credentials
        env:
          NCP_USERNAME: ${{ secrets.NCP_USERNAME }}
          NCP_PASSWORD: ${{ secrets.NCP_PASSWORD }}
          NCP_REPO_URL: ${{ secrets.NCP_REPO_URL }}
        run: |
          echo "https://${NCP_USERNAME}:${NCP_PASSWORD}@devtools.ncloud.com" > ~/.git-credentials
          git config --global credential.helper store
          git config --global user.name "contents67"
          git config --global user.email "tom990422@gmail.com"
          git remote remove origin || true
          git remote add origin "${NCP_REPO_URL}"

      - name: Mirror push to NCP SourceCommit
        run: |
          echo "Pushing all branches and tags to NCP..."
          git push origin --all || (echo "Push failed. Exiting..." && exit 1)
          git push origin --tags || (echo "Push failed. Exiting..." && exit 1)
